### ISSUE TITLE
Link to pages using page id in url

### ISSUE THREAD

**Issue by snazzyDocs** [snazzyDocs/public-snazzyDocs#49]
^

**Comment by matthiaseinig** [comment]
Eventually this would be permalinks like in Wordpress. 
I suppose a url parameter would be sufficient https://docs.mydomain.com/?p=< pageid >

In an optimal case that would redirect to the actual url of the page (or a 404 page if not found/published)

**Comment by snazzyDocs** [comment]
> Eventually this would be permalinks like in Wordpress.

Just so I'm 100%... Are you talking about the "Pretty permalinks" setting in Wordpress? https://www.wpbeginner.com/glossary/permalinks/

**Comment by matthiaseinig** [comment]
Sorry, no, it is sufficient to just be able to pass the id to a page and get redirected to the correct page url. 
There is no need to prettify the, as it is just supposed to be an entry point to have a fix url, that is never changing, even if the page gets moved

**Comment by snazzyDocs** [comment]
Will be available on next update

**Comment by matthiaseinig** [comment]
It is unclear how this is working assuming this has been already released.
Neitther ?p=<id> nor ?id=<id> is working and in the admin backend I don't see an option to just copy the permalink, eg. in the share menu or in the ToC context menu.

**Comment by snazzyDocs** [comment]
> It is unclear how this is working assuming this has been already released. Neitther ?p= nor ?id= is working and in the admin backend I don't see an option to just copy the permalink, eg. in the share menu or in the ToC context menu.

It's not released yet.

**Comment by rogerraa** [comment]
Released...

**Comment by snazzyDocs** [comment]
Released...
