### ISSUE TITLE
Generate Sitemap Urls for Google Indexing

### ISSUE THREAD

**Issue by matthiaseinig** [snazzyDocs/public-snazzyDocs#53]
It would be helpful if Snazzy would generate a sitemap.xml on every publish (or dynamically) that could be referenced in the Google Search Console, so that Google always knows which pages to regularly re-index. 

for example accessible always under docs.customer.com/?sitemap

Documentation how the Sitemap should look like can be found here
https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap

**Comment by snazzyDocs** [comment]
Good to hear someone else is thinking about this! :)

This is something I've thought about, and researched a little bit a few times. I didn't dive very deep as I'm not sure how necessary sitemaps are for SPA's (that is effectively what the snazzyDocs snippet provides).

My thinking thus far is to explore this for the static site generation hosting, and if possible make it work with the SPA snippet.

**Comment by matthiaseinig** [comment]
I guess from the Google perspective this is not an SPA, as each page has its own url and content. Hence Google needs to crawl each one of them. Of course it can do that by following all links in the TOC, but that is usually much much slower in terms of getting the content updated in the index after a change, instead of telling Google search console the sitemap location and it checks in the sitemap when each page has been last modified. 
That way google only indexes the changes. 

Format wise this is pretty simple as you can see here https://www.sitemaps.org/protocol.html
Just a bunch of url nodes with 
```
<url>
   <loc>https:/..... </loc>
   <lastmod>timestamp</lastmod>
</url>
```
...

**Comment by snazzyDocs** [comment]
Hey @matthiaseinig can you please try this out and let me know how it goes?

As you suggested, publish your doc to generate the sitemap.xml file, then try adding your docs domain with the `?sitemap` to Google Search Console.
So `https://docs.yourdomain.com?sitemap`

If all goes well, this is good to go for an open beta.

**Comment by snazzyDocs** [comment]
Feature beginning open beta

https://docs.snazzydocs.com/1.0/hosting/sitemaps
