### ISSUE TITLE
PDF export enhancements

### ISSUE THREAD

**Issue by rrasill** [snazzyDocs/public-snazzyDocs#54]
It would be great to add the capability to add a picture in the first page and also to add the company logo in the rest of the pages when exporting to pdf.

**Comment by snazzyDocs** [comment]
Yes I agree, these would be great additions. There are future plans to flesh out the PDF export with exactly these kind of features. I will be sure to explore the viability of these additions when that happens.

**Comment by snazzyDocs** [comment]
Task assigned to #69
