### ISSUE TITLE
Illegal character in general slug

### ISSUE THREAD

**Issue by perholmes** [snazzyDocs/public-snazzyDocs#60]
Hi,

Bug report. I had a page title with a question mark, which generated a slug for the page like "what-is-productname?". That page shows up as "Page Not Found". The question mark can't be resolved somewhere along the way. It should simply be sanitized out when generating slugs.

**Comment by snazzyDocs** [comment]
Agreed...

Will be fixed shortly.

**Comment by snazzyDocs** [comment]
? characters will now be removed on "slugification".. Thanks for the heads up!
