### ISSUE TITLE
Extra line always inserted before image

### ISSUE THREAD

**Issue by perholmes** [snazzyDocs/public-snazzyDocs#61]
Hi,

I'm facing an annoyance when creating a lot of documentation, that when you paste an image, an additional empty line is always inserted before it. The only way to avoid this is to paste the image at the end of the previous line, which isn't natural. Consequently, a certain amount of my actions is cleaning this up for every single image.

I don't think you should insert a blank line before images. If I had pasted text, there would be no question that an empty line before would be wrong. I think the same logic should apply to images, that they get pasted on the line you're on.

**Comment by snazzyDocs** [comment]
I agree completely. If I remember correctly there was some difficulty with these new lines during development of the image module. But I will give it another try.

Thanks for the feedback!

**Comment by snazzyDocs** [comment]
The image module has been adjusted to insert images without a blank line before them.
_*Please note - One thing worth mentioning... images that are inserted while the cursor is on an existing line of text will be inserted as an "inline image" by default._

I will close this for now, but please feel free reply to this issue if you experience any more "bugs" related to this, and I'll re-open it straight away.
