### ISSUE TITLE
Workflow polish around creating links

### ISSUE THREAD

**Issue by perholmes** [snazzyDocs/public-snazzyDocs#62]
Hi,

Currently, in order to create a link, you have to first open the link menu and select internal page link. This opens a dialog, which doesn't have the search field selected, so you have to move the mouse again to select the field. Now you can type and select search results, but pressing Enter doesn't select them, it only closes the dropdown menu. And pressing Enter again doesn't select the purple Insert button, it opens the dropdown again.

This is very inconvenient, and you kind of fall over your own feet over and over. Ideally, you could make these changes:

1.) An internal page link is a top-level button in the toolbar, so you don't have to open a menu. It would also be better if you could create an internal link via right-clicking the selected text, or a keyboard shortcut.

2.) When the dialog is opened, the text field should already have focus.

3.) When an item is pressed in the dropdown, the dialog should be submitted with that selection. If people don't want to select anything, they can use Escape to cancel or click outside the dropdown menu.

When you have to do this a lot, it's quite painful with the almost double number of steps needed.

Thanks!

**Comment by snazzyDocs** [comment]
I like it!

I'll see what I can do.

**Comment by snazzyDocs** [comment]
Done... _(with a couple of caveats)_
https://docs.snazzydocs.com/1.0/the-editor/text-editor/shortcuts#links

1. Link to page button will not be added as a separate toolbar item.
2. For now, pressing enter OR clicking on a page option in the "Link to page" modal will insert without having to hit the Insert button. Ideally, clicking would not insert, but pressing enter would, but I was unable make that work at this time. In the future I hope to do this ideal functionality.

**Comment by perholmes** [comment]
It's good enough for sure, now the tool change is gone, and it's a lot smoother.

If it at some point got a keyboard shortcut, it would be possible to set up links just with the keyboard.

**Comment by perholmes** [comment]
Honestly, this new workflow is a dream. Just a couple of keystrokes to link to another page.

**Comment by snazzyDocs** [comment]
Just to be clear... There are keyboard shortcuts now for both URL links and Link to page popups.

**URL link:** CTRL/CMD+SHIFT+L
**Link to page:** CTRL/CMD+SHIFT+ALT+L

**Comment by perholmes** [comment]
It seems that I've led you a bit astray, because isn't it more difficult to create permalinks now? I don't know if it was possible in the page link editor before, but it's definitely not now. We're running with the # symbols disabled, and it's possible this was the only way to get automatic permalinks before.

But it seems that it should be possible to create permalinks in the dialog where page links are created, basically in a second text field underneath where you can type the permalink, or even better, get a drop-down of H2 tags on the selected page.

The compromise would then have to be that Enter in the drop-down doesn't close the dialog, it only closes the drop down. Then you can press Enter again to confirm the dialog, or you can Tab down to also create a permalink. That seems like I would be pretty smooth and transparent.
