### ISSUE TITLE
Ctrl+S to Save or Publish

### ISSUE THREAD

**Issue by perholmes** [snazzyDocs/public-snazzyDocs#63]
Hi,

It would be great if Ctrl+S could be intercepted and used for publishing the draft or the final output, depending on the current publishing settings.

I tend to want to see the final result to be able to judge it, and I go an awful lot to the Public button, which is multiple mouse clicks and a tool change. I also keep hitting Ctrl+S, which opens a Chrome HTML save dialog. Ctrl+S is so much a motor memory that it's hard to remember isn't supported.

I realize that making it easier to publish might put slightly more pressure on your servers when the static output is generated. But consider that this will be super light weight in the real world. It only happens when you edit the docs. Most of the time, docs are just sitting there with no one editing them. So I don't think this will increase your CPU bill.

**Comment by snazzyDocs** [comment]
Great idea... I hit CTRL/CMD+S all the time as well!

I do have one slight tweak though. I'm definitely going to try this for the publishing button. (Drafts are autosaved after changes so a shortcut is not needed there).

My only concern here is people hit the shortcut out of "motor memory" and end up publishing content that isn't ready for the live doc yet. There is the Publish Protection toggle switch, so I'll see if anything cool can be done with that.
<img width="244" alt="image" src="https://user-images.githubusercontent.com/40471375/160189275-2da62995-c7f6-46ca-8aa0-f22b79b58f67.png">

I'll give it go...

As an aside, I will also attempt to make a shortcut for Previews...


Thanks for the awesome ideas, keep em coming!

**Comment by snazzyDocs** [comment]
Done...
https://docs.snazzydocs.com/1.0/the-editor/text-editor/shortcuts#general-editor

As for the Publish Protection implementation, I decided to keep it simple for now, without any added functionality. It will be up to users to preemptively toggle the Publish Protection toggle switch on to prevent accidental publishing.

**Comment by perholmes** [comment]
This is a super smooth workflow for me.
