### ISSUE TITLE
Collapse/Expand All

### ISSUE THREAD

**Issue by perholmes** [snazzyDocs/public-snazzyDocs#64]
Hi,

In the editor, I miss a way to easily collapse or expand all topics. Ideally, it would just be two small icons next to the Full Screen and Collapse Panel icons.

**Comment by snazzyDocs** [comment]
I have been wanting the add the same thing, but could never find a "good" spot to put it. Up near those two small icons could work. I'll try it and see how it feels.

Thanks!

**Comment by snazzyDocs** [comment]
A new button has been added with the following dropdown menu items; Collapse all, Expand all, Expand to chapters.
<img width="489" alt="image" src="https://user-images.githubusercontent.com/40471375/160292941-4be8efb6-016b-43b3-9604-eee07087298f.png">

As an aside.. I'm not 100% on the icon choice(ie. List). <img width="28" alt="image" src="https://user-images.githubusercontent.com/40471375/160292719-c818941e-6585-4825-9833-6317ef07bb53.png">

A couple I was also considering;
Drawer: <img width="26" alt="image" src="https://user-images.githubusercontent.com/40471375/160292756-8c8fbb82-2b0c-415b-904e-fb12cea100e7.png">
Format_1: <img width="27" alt="image" src="https://user-images.githubusercontent.com/40471375/160292811-3d2bc520-bf3b-4e60-92ed-c07e63dd9792.png">

Any thoughts on the icon choice would be greatly appreciated.

**Comment by perholmes** [comment]
I'm actually on board with the icon. I've had to come up with expand/collapse icons several times, and it seem logical when you're making them, but then in real use, you're like "what's that".

A menu says that it's a menu. It can contain many things, including expand collapse. It's not single-click, but still a lot faster than collapsing everything by hand. I'd leave it for now and see how it goes in real use.
