### ISSUE TITLE
Image quality

### ISSUE THREAD

**Issue by perholmes** [snazzyDocs/public-snazzyDocs#65]
Hi,

I'm starting to be a bit concerned about image quality. All of our images are a little bit fuzzy, indicating aggressive compression, which isn't great for UI.

Would you consider a setting to increase this? Also, when you paste images, do you keep the original image on your servers, or is the quality immediately and irrevocably lost?

And if you copy and image from one page to another, are you actually copying the already compressed image, and then it gets compressed one more time on paste? Since it's not clear, I've been copy/pasting the text around the image in the hope that the clipboard is your own format that keeps referencing the same image. I assume that the right-click Copy Image function is provided by the browser, and therefore the pasted imaged is recompressed.

**Comment by perholmes** [comment]
Actually, I might be wrong about all of this. I'm working on a High DPI monitor, but the screenshots are being done on a regular Low DPI monitor. So I'm seeing Low DPI screen captures along with High DPI text. When I view the docs on a Low DPI monitor, I don't get the same sense that the images are heavily compressed.

Still, I'm interested in the best way to copy/paste images between pages without recompression.

**Comment by snazzyDocs** [comment]
> Would you consider a setting to increase this? 

While I'm open to exploring some kind of setting in the future, for now I recommend taking screenshots on High DPI monitors. That is what I do.

> ...when you paste images, do you keep the original image on your servers, or is the quality immediately and irrevocably lost?

Images are automatically compressed upon upload.

> ...if you copy and image from one page to another, are you actually copying the already compressed image, and then it gets compressed one more time...

> Still, I'm interested in the best way to copy/paste images between pages without recompression.

Yes I believe to a certain point the images would be "re-compressed". Instead of copy pasting images from one page to another, use the Media Library to insert already uploaded images. https://docs.snazzydocs.com/1.0/the-editor/text-editor/images

As an aside, the media library needs some big improvements that will be coming at a later date.

**Comment by perholmes** [comment]
Hi,

I don't think a media library cuts it for copy/pasting content that contains images from one page to another. Digging through a media library to replace the images with the library version would be extremely uphill. We're probably talking 5-10 minutes per image of digging methodically through a media library to find the right one, especially when there are similar images.

To be honest, I don't think the media library should exist. It's the same as in any CMS, there are hundreds or thousands of images in a selector with tiny thumbnails that load slowly, and it's bordering on impossible to be productive with it. It is a truly massive attention hog, and you'll completely have forgotten what you were working on when you finally find the image. Everyone just uploads new images all the time. You should seriously consider not having a media library at all, and just garbage collecting unused images.

As for avoiding recompression on copy/paste, you could tag images with some internal ID metadata, so that if an IMG shows up with this ID, the upload isn't used, but it's instead referenced in the library.

**Comment by snazzyDocs** [comment]
Yeah, while I might agree to certain points you made about whether or not to have media library, for now, my main goal is to see how snazzyDocs can work better for your preferred use case of copy/pasting images from one page to another.

Again, you have very good points about the validity of even having a media library, which I 100% appreciate. When it comes time start working on the design/functionality changes I have planned for it, I will take the points you made and reassess before any major coding is done.

It's an interesting idea about the image internal ID metadata, and I will look into to it.

Thanks!

**Comment by perholmes** [comment]
Totally OK, you'll make the right choice, I'm just trying to add all the use cases to the picture.

I do quite a lot of copy/pasting between documents as I decide what should be covered on which page, and I gather that this actually means recompression every time. So that's the most important part to address.

**Comment by snazzyDocs** [comment]
Quick update...

After digging in a bit, this is a little bit more nuanced that I had hoped. There are a bunch of different edge cases that I need to factor in.

That said, I'm still working on it.

**Comment by snazzyDocs** [comment]
The image meta data route was(long story short) unfortunately rife with complexity.

I'm testing a much simpler approach using perceptual hashing of images. Uploaded images are compared to existing images(with phash's) already stored for the doc. If the similarity reaches a set threshold, the image is not optimized, nor stored.

This handles the multiple optimization issue, as well as allows for one image being in multiple pages without needing multiple image files. Essentially, resulting in the same functionality as the "insert" method, but without needing to use the Media library. So kinda neat...  

Anyway, still finalizing with the testing... Will update soon.

**Comment by perholmes** [comment]
That's very cool!

**Comment by snazzyDocs** [comment]
Alrighty...

This is now available for beta testing. Please send a message using the In-app chat so that I can get your snazzyDocs account email address and I'll add you to the closed beta list.

A new issue has been created to guide the beta, let's continue the discussion there. #70

**Comment by snazzyDocs** [comment]
Closing... If you are unsure how to message me using the In-app chat, please let me know.
