### ISSUE TITLE
Removing color

### ISSUE THREAD

**Issue by perholmes** [snazzyDocs/public-snazzyDocs#66]
Hi,

When pasting text from another document (another app), the color seems hard-coded into the rich text, and seems impossible to remove. I'm familiar with this because our product has a complex text editor that has had the same problem, that once a color is assigned to the span of the text, it overrides any colors you try to assign.

In this pasted text, I'm unable to get links to show in their natural CSS color. I have to round-trip the text to Notepad++ in order to remove the formatting.

A couple of options come to mind. One is that you have settings somewhere for what is actually pasted, which could include Font, Color, etc. Another is that you show a gizmo around the paste like Word, allowing people to paste only Text or Text + Formatting.

But it doesn't help if the user themselves has assigned a color to text. You should have a separate color option for "Default Color" or "None". You could make it as a circle like the other swatches, but with a red cross inside of it, to indicate "no color".

**Comment by perholmes** [comment]
I did manage to remove formatting with the remove formatting button (duh), but there's still some markup stuck. Here is the text with formatting removed:

![image](https://user-images.githubusercontent.com/4181396/160234196-b7c76c7a-29e3-49f9-b5ef-dfcc8780143d.png)

But the whole paragraph is still somehow one span, or there's a bug in breaking the span. Changing it to H2 still changes the whole paragraph:

![image](https://user-images.githubusercontent.com/4181396/160234236-94e9fc80-c512-40fd-9a9b-c019bb5221d4.png)

**Comment by perholmes** [comment]
Found the remove formatting button, so duh.

I would still like the option of pasting without formatting. Basically, half of this text is coming from Dr.Explain, and it's littered with formatting in the clipboard text.

**Comment by perholmes** [comment]
Strike that, simply pressing the remove formatting button is not a big enough obstacle that you should bother to make UI for it.

**Comment by snazzyDocs** [comment]
Hey,

You can paste without formatting using CTRL/CMD+SHIFT+V :)

Also, take a look here for some of the other common gotchas. https://docs.snazzydocs.com/1.0/getting-started/common-gotchas

I'll leave this open for now in case I missed anything you said.

**Comment by snazzyDocs** [comment]
Closing for now. I can reopen if needed
