### ISSUE TITLE
PDF Output

### ISSUE THREAD

**Issue by perholmes** [snazzyDocs/public-snazzyDocs#67]
- Hi,

This is a longer term feature request. I realize that you can't just make a quick tweak.

Our previous documentation system was Dr.Explain, which for all its flaws could also output a PDF of the documentation. Some users prefer to get a PDF that can be read offline on any device.

If you were to do something similar, I just wanted to say that the Dr.Explain implementation was terrible, and even that was better than no PDF. Basically, they were just dumping the pages into a PDF with a bit of wrappers.

The problems with their PDF output was:

- The scale was wrong. The text and images were too big, with no way to scale them, causing very little to actually fit on each page. It should have a feature called something like "Print Scale", defaulting to 100%, that reduces font and images sizes.
- The page/image breaking was often wrong. There should be a global preference for whether to keep images together with the preceding or following text in general. This is basically to avoid orphaned text with the image on the next page.

Having worked on these kinds of layout engines, it's not 100% trivial to lay out the text in a pleasing way. But if you'd like to try one day, we know that some users prefer it.

Most likely, making PDF docs should be on the same lifecycle as your offline download, that it's user-initiated. Although the nicest, of course, would be the ability to put a PDF download link into the docs themselves.

Anyway, just planting a flag.

**Comment by snazzyDocs** [comment]
There is a PDF export currently in beta. (I have just added a section in the snazzyDocs docs; https://docs.snazzydocs.com/1.0/managing-your-docs/exporting)

Also worth mentioning, there is another open issue regarding the PDF export to be aware of: #54 

As for how it compares to your previous documentation system's export, I'm curious what you think. Give it a try.

**Comment by perholmes** [comment]
Hi,

This already works extremely well! The scale that you export at is appropriate for printing, so you fit more on a page, and there aren't as many obviously orphaned paragraphs.

But it would definitely look better with some orphan-control, to avoid a title at the bottom of a page and then the content continuing on the next page.

I have a few thoughts about how to make a layout algorithm that doesn't actually require you to do a layout ahead of time in order to decide if it will fit on a page. Most likely, you're using a PDF library, and you don't even have direct insight into the layout process.

But if the goal is just to make it prettier, you can guess ahead of time whether you need to break to another page based on other heuristics.

For example, since you're probably printing one paragraph at a time to the PDF library, you can for example make a rule that you're unwilling to start a new H1/2/3 title if you're more than 85% down the height of a page. It's not intelligent like Word, but it'll do.

And in the same area of the bottom 15% of a page, you can make a rule that if you have an image coming up within e.g. 200 characters, you wrap to the next page before printing the next paragraphs.

Point is just to have some logic where you can guess the future via heuristics instead of actually doing a layout in order to see if it works. The rules could be different. Just avoid doing actual layout calculations, it's an endless rabbithole.

**Comment by snazzyDocs** [comment]
Yes, snazzyDocs uses a HTML to PDF library, which takes full HTML document and automatically fits each page of a snazzyDocs doc into however many PDF pages it can(ignoring what it put where).

I 100% get what you are saying about "orphan" items due to heading elements starting too low down on the page. I experimented a bit in the beginning with some logic to influence this behavior, and you are right... it was a rabbit hole, that I eventually leaned away from. :)

Having said that, I do think it deserves some more time exploring. Thanks for the ideas.

**I will leave this open as a placeholder for this topic surrounding "orphan-control".**

**Comment by perholmes** [comment]
Maybe also check the docs for this PDF library whether it's possible to hint the HTML to inject layout preferences, like keeping paragraphs together.

**Comment by perholmes** [comment]
Couldn't help looking into this, and there might be some options for how to arrange the HTML so that it breaks in the right places during unsupervised layout. I've used DomPDF (https://github.com/dompdf/dompdf) before, and it says that it honors these tags.

Basically, it's possible to wrap content in a div, and then set "break-inside: avoid;" on that div. One approach could then be an HTML preprocessor that looks for paragraphs to cluster together into divs with this break-inside:avoid. 

This is not to tell you how to write code, But if every single paragraph is put into its own div, there's a simple loop.
 
* Iterate paragraphs
* If paragraph follows an H tag, put it into same div as previous paragraph
* If paragraph is an image that follows a non-image, put into same div as previous paragraph\
* Otherwise end existing div and start a new one.

Anyway, it's probably more complicated in reality, just spitballing.

**Comment by perholmes** [comment]
Or alternatively, still not telling you how to write code, if every single paragraph is put into its own div, there's a simpler loop.
 
* Iterate paragraphs
* If paragraph follows an H tag, put it into same div as previous paragraph
* If paragraph is an image that follows a non-image, put into same div as previous paragraph\
* Otherwise end existing div and start a new one.

Anyway, it's probably more complicated in reality, just spitballing.

**Comment by snazzyDocs** [comment]
Right on! Yeah I looked in the library's docs for anything regarding this and didn't find anything. I'll look through their GitHub issues for the break-inside: avoid; thing.

Just so we are clear... this is what we are trying to prevent?
<img width="822" alt="image" src="https://user-images.githubusercontent.com/40471375/160290275-6b15028f-6ec1-44e6-b8b8-ed921fc82750.png">

**Comment by perholmes** [comment]
Yes, partly. The example you posted is a classic orphan, which would be resolved if you simply added a tag to never break inside. But this is still just the handling of one single paragraph.

My concerns are one level up, that I'd prefer a heading to not appear alone as the last line on a page.

And I would prefer that images don't lose the text immediately above it. The thing is that a paragraph is often small and an image is often large, so it's highly probably that the image exactly rolls over to the next page, but the paragraph still fits on the previous page. So the issue of images getting separated from their description is extremely common, and bad.

So this is why I'm trying to suggest some kind of simple clustering algorithm that can be done just on the paragraphs, by making sure that headings at least stay with the first paragraph after them, and that images at least stay with the preceding text paragraph.

**Comment by snazzyDocs** [comment]
Alright... Items after headings are wrapped into "groups" with the page-break-inside: avoid; css property.

I did a little bit of testing and seemed to work pretty good, but let's see how it handles in the wild.

It creates groups starting with wrapping H6, then H5, and so on, until H1. It does not wrap items into a H1 group.

**Comment by perholmes** [comment]
That's remarkably effective. It almost looks like a human went through it and broke pages in logical places.

I assume you're not doing anything for keep images together with descriptions yet, because I have a number of these:

![image](https://user-images.githubusercontent.com/4181396/160442711-ab6b6cdf-0c6d-4a40-9278-bf5ffe0b4e95.png)

There's some debate to be had whether descriptions are reasonably expected to go before or after images. I find that before is better, because otherwise you're just being served an image without knowing why you're seeing it. I don't think we can think in captions in a newspaper sense where the text is after the image, because such a caption is only supplemental. I think that in docs, there's some important description that goes before the image itself.

So that's why I thought the logic might work that if an image has a normal text paragraph before it, the image adds itself to that div.

**Comment by snazzyDocs** [comment]
Yeah, currently there are no image specific rules in the grouping algorithm.

I'll think about what you are proposing.

**Comment by snazzyDocs** [comment]
At this time there is no plans/way to add the kind of control proposed regarding image descriptions. Closing for now
