### ISSUE TITLE
PDF Hosting

### ISSUE THREAD

**Issue by perholmes** [snazzyDocs/public-snazzyDocs#68]
Hi,

Would you consider an ability to host the PDF along-side the generated documentation? The problem for us is that we're all Docker Containers and CDNs, and it's actually not easy for us provide access to the PDF. I'd basically have to log into an S3 bucket and upload it every time it changes.

I don't mind having to proactively generate the PDF. It seems CPU intensive, and I understand why you'd not want to generate it on every save. But we really have no straightforward way to host it.

**Comment by snazzyDocs** [comment]
Yeah I would totally consider it... it's a great idea! It needs to be implemented for another feature anyway.

I'll attach this to #54

**Comment by snazzyDocs** [comment]
Task assigned to #69

**Comment by perholmes** [comment]
This is becoming a core issue from our perspective. Basically, without PDF hosting, on every update, I have to download the PDF, get through security to AWS in order to upload the PDF in a bucket, then either log in to CloudFront to invalidate the whole CDN, or upload it under a new name, and change all website and in-app links, which includes going through a release cycle on all platforms.

In other words, self-hosting the PDF is a huge task, and the sooner you work something out, the better.

* I'm perfectly fine if you have to manually click to generate the PDF. It's CPU intensive, and you don't want it running on every save.

* The hosted PDF should retain its filename, so that apps and weblinks can link directly to the latest documentation. Perhaps bake the language into the name, so that you can direct-link to PDF documentation in multiple languages. If you create this using ISO codes append to the PDF name, so that the naming is consistent, we can even send people to the right documentation depending on their selected app language. But the multiple language thing is over-shadowed by the need to have it hosted at all, and the task shouldn't stall on that.

**Comment by snazzyDocs** [comment]
So yeah, as I said before this would need done anyway for a different feature... If it'll make your life easier, I see no reason why this can't be done now.

I'll post back soon with an update.

**Comment by snazzyDocs** [comment]
Okay...

PDF's will now be hosted, and viewable via a public link. `https://app.snazzydocs.com/docs/[id]/pdf`, or downloadable with an optional url parameter `?dl=1`.

For now the link is automatically copied to your clipboard when exporting.

**_*DISCLAIMER - Functionality of acquiring the link and physical link route/syntax is subject to change at a later date when the other feature I mentioned previously begins development._**

Please give it a go and let me know if you have any issues.

**Comment by perholmes** [comment]
I'd like to understand the risk in using the feature now. First, does the ID change on every export? And what happens when you move to another way of hosting.

Basically, the purpose of the PDF is to direct-link to it from an app. Even if we update the app as soon as you change the URL structure, there will always be people who don't update, or who don't update fast enough. Without an URL that's stable over time and is always the same for every export, it wouldn't be reliable to direct link to the PDF from an app.

So as much as I love that you're doing it, I'm concerned that we won't be able to use it yet.

**Comment by snazzyDocs** [comment]
The id does not change..  The id in the url is the unique id of the documentation.

This means, regardless of how or where the pdf file is hosted, public link will always point to the PDF file.

**Comment by perholmes** [comment]
But to be clear, will the URL change? Or do you believe this to be the final location?

**Comment by snazzyDocs** [comment]
Friendly reminder here, I'm skipping a bunch really important steps(R&D, prototyping, testing, etc.) of the previously mentioned pending feature to help the issue of having to host the PDF yourself.

But none the less...  No, I don't foresee it changing.

Obviously I'll try my best to avoid it, but I cannot predict the future requirements of an unbuilt feature. Worst case, you have to update your link once.

**Comment by perholmes** [comment]
Sure sure, it's only that if I direct link to the PDF and this changes substantially, I'll have deployed apps that point to a dead link, some of which I can't get updated no matter what I do. I think it might be safest that I wait for the feature to stabilize and confirm that you're settled on the current approach. It's not to minimize the effort of doing this quickly, I just have a bit of cold feet about using it in production, which is also the only place where the feature matters.

It's just enough of a problem with people not updating that we've specifically built a nag-level mechanism so that we can eventually force people to run the app with a constant update prompt that they can't close. And some people keep running with that. The reality is that even if it's an old version pointing to potentially dead docs, they'll still see any problem as the app's fault.

I could make a redirect on our end, in case the location ever changes. Then we have a guaranteed constant link to hand out.

**Comment by perholmes** [comment]
Hi,

I was wondering if you had landed on a format for permalinks for hosting PDFs? I'd like to link directly to a PDF from within the app, but if the links change, it can take us up to a year to get old versions of our app flushed out. So it's important with a hyper-stable permalink.

I'll definitely route through a redirect link on our website. But I'd still love to know if the PDF permalinks are considered stable for now.

And actually, what are the links? Simply the link where I get the PDF download?

**Comment by snazzyDocs** [comment]
Hi,

Yeah go ahead and consume. I'll make sure the link remains valid for you.

Link will be https://app.snazzydocs.com/docs/[id]/pdf, and downloadable when an optional url parameter ?dl=1.

**Comment by snazzyDocs** [comment]
Done.

https://docs.snazzydocs.com/1.0/managing-your-docs/exporting#subsequent-pdf-retrievals
