### ISSUE TITLE
Critical issue, page going back in time

### ISSUE THREAD

**Issue by perholmes** [snazzyDocs/public-snazzyDocs#73]
Hi,

I had something highly destructive happen today. A long page I was working on suddenly went back to its state from about 12 hours ago, reverting a lot of work.

I have not had SnazzyDocs open in multiple tabs, at least I strongly believe I haven't. In the global history, there's a commit this morning with a much older version. And strangely, the Page History is empty.

There are a couple of things that keep me from effectively dealing with this. First, there appears to be no way to restore a page from the global history. This would be the most urgent feature request from me. Instead, the only record I have of my work is copy/pasting from the global history display, but this is rendered HTML, and the images have span tags in them, which I have to manually remove. I also have to check if the image links are actually the same or whether they'll get recompressed. And I have to remove all the red/green change indicators by hand. Either way, this is highly destructive, and I think a critical feature would be the ability to restore from the history page.

Secondly, if we assume that I did have multiple browser tabs open (unlikely, but technically possible), I think it's important to mitigate this to prevent submitting an old version on top of a new version. I see that you deal in commits internally. My recommendation would be that each tab knows the commit it's forked from, and if you're trying to create a branch as a single user, you should be prevented from saving without confirming that you intend to overwrite a new version with an old version. Either that, or you create a unique branch for each instance of the same user.

**Comment by perholmes** [comment]
Or as a very quick mitigation, you could require SnazzyDocs to only run in a single tab for that user, and lock out other tabs.

**Comment by snazzyDocs** [comment]
This is going to be a tricky issue, that I will need your help to recreate. Until we can recreate it I can't be 100% sure its about multiple tabs.

As for restoring/mitigation there is a huge update coming that is complete overhaul of the data store and history. It will allow for much more possibilities for restoring. Further, if you would like some help manually restoring the lost bits, just let me know via the In-app chat.

But in the meantime, Any help you can do to recreate it would help tremendously, so I can begin troubleshooting. I'm also going to attempt to recreate this.

As an aside, if you would like to join the closed beta of the new updates I spoke of let me know.

**Comment by perholmes** [comment]
I don't know how it happened, but i don't think it was multiple tabs. The file was just suddenly where it was at some point yesterday afternoon. The browser tab had been left open overnight. It's the only time I've seen it, and I have no leads.

I managed to reconstruct the page from the previous version in the global history, which meant removing a lot of markup. But the page is good now. I created a new page for the reconstructed result and renamed and disabled the old page, in case you're interested in looking at the exact page where it happened. Let me know how to communicate its ID.

**Comment by snazzyDocs** [comment]
Alright.. My suspicion is it's somewhere in the expired session handling. For now, unless you are actively trying to recreate the issue, close the editor when you stop editing.

Do you remember getting the "Session has expired" popup when coming back to the tab that morning?

**Comment by snazzyDocs** [comment]
Quick update...

I think I have tracked down the culprit. I have also added an extra check (on top of the other checks) to prevent this.

I will leave this open for now...

**Comment by perholmes** [comment]
Hi,

OK. That's the only data point that seems to make sense. I very much doubt that I was running in multiple tabs, but I did leave it open overnight.

**Comment by perholmes** [comment]
Hi,

I have a new data point about how data could be lost because I did something by accident.

I had written two new pages, including saved several times. I then accidentally clicked a bookmark, loading a 3rd party page. When I clicked the back button, both of the pages I had just written were blank, even as I clicked back and forth between them. However, after reloading SnazzyDocs, my work was there on both of these pages.

If we consider that those pages were actually blank because that was the earlier version, and if I then went on to edit them, I'd now find these pages missing information, which I'd be committing to when now saving.

So perhaps there's something wrong about which state is loaded when you navigate backwards, which is probably a lighter state restore in the browser than an actual reload. I'm using Chrome.

**Comment by snazzyDocs** [comment]
Oh, interesting.. I'll try to recreate. Good stuff, thanks!

**Comment by snazzyDocs** [comment]
Was able to reproduce consistently...  :pray:

I have disabled browser cache for the editor for now until I can find a more elegant way of solving for.

**Comment by snazzyDocs** [comment]
Disabling browser cache for the editor has fixed the issue. Closing for now, until a better fix is found.
