### ISSUE TITLE
Facebook/Twitter image tag

### ISSUE THREAD

**Issue by perholmes** [snazzyDocs/public-snazzyDocs#78]
Hi,

It would be lovely if SnazzyDocs could include Facebook/Twitter/LinkedIn sharing image meta tags to make them visible while sharing.

I'm sure you know, but here's a summary: https://blog.hubspot.com/marketing/open-graph-tags-facebook-twitter-linkedin

You could simply have a single user-uploadable image for the entire document, i.e. you wouldn't need to generate an image for every single manual page. So this would be much easier for SnazzyDocs than it normally is in web development.

This came up a few times where someone asked questions on our Facebook page and I wanted to post a link to a manual page. It also comes up when tech support is done via social media chat. The document links look very naked and incomplete currently. Outside of this use case, obviously it isn't critical.

**Comment by snazzyDocs** [comment]
Duplicate #76
