### ISSUE TITLE
Missing images on page

### ISSUE THREAD

**Issue by perholmes** [snazzyDocs/public-snazzyDocs#93]
Hi,

One of our pages has mysteriously lost all its images, both in the editor and the rendered output. It's only one page apparently, and everything was there the last time I looked 6 months ago. What do you need in order to troubleshoot this?

Per

**Comment by snazzyDocs** [comment]
Hey Per,

I'll need the page in question. Can you copy/paste the url while on the page in the editor please?

**Comment by perholmes** [comment]
But just here publicly?

**Comment by snazzyDocs** [comment]
It would be fine yes, but if you prefer you can paste it to me via email(support@snazzydocs.com) or in the In-App Chat.

**Comment by perholmes** [comment]
Emailed.

**Comment by snazzyDocs** [comment]
Okay. I'll investigate and get back to you soon.

**Comment by snazzyDocs** [comment]
Replied to you via email.

**Assessment:**
The images were hosted on another server and were missing.

**Follow up**
Externally hosted images are not tracked by snazzyDocs. A new issue #94 has been created to explore how this could be prevented in the future.

This post will be closed sometime in the near future.

**Comment by snazzyDocs** [comment]
Images have been re-added to the page and are now hosted on the snazzyDocs server.

**Comment by perholmes** [comment]
All set
